### listar
GET http://localhost:3000/clientes

### crear
POST http://localhost:3000/clientes
Content-Type: application/json

{
  "id_user": 3,
  "actividad": "Productor agrícola",
  "ingresos_mensuales": 150000
}

### detalle
GET http://localhost:3000/clientes/7

### update
PUT http://localhost:3000/clientes/7
Content-Type: application/json

{
  "cuil": "20-46537774-8"
}

### delete
DELETE http://localhost:3000/clientes/3
