GET http://localhost:3000/user

###Get one user
GET http://localhost:3000/user/john.doe@example.com

###Post User
POST http://localhost:3000/user
Content-Type: application/json
{
  "name": "Jane Smith",
  "email": "jane.smith@example.com",
  "age": 28
}

###Get one user
GET http://localhost:3000/user/jane.smith@example.com

###Delete user
DELETE http://localhost:3000/user
