### Obtener todas las provincias
GET http://localhost:3000/provincias
Accept: application/json

###

### Crear una provincia
POST http://localhost:3000/provincias
Content-Type: application/json

{
  "nombre": "Test"
}

###

### Obtener provincia por ID
GET http://localhost:3000/provincias/1
Accept: application/json

###

### Actualizar provincia
PUT http://localhost:3000/provincias/13
Content-Type: application/json

{
  "nombre": "Test Actualizada"
}

###

### Eliminar provincia
DELETE http://localhost:3000/provincias/13
